markdown: redcarpet
permalink: /blog/:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - favicon-16.png
  - favicon-32.png
  - README.md
  - bin
redcarpet:
  extensions:
    - no_intra_emphasis
sass:
  style: compressed
